# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
